version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper

# Move into Kafka container
# docker exec -it <kafka_conatiner_id> /bin/sh
#
# Go inside kafka installation folder
# cd /opt/kafka_<version>/bin
#
# Create Kafka topic
# kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic default-topic
#
# Start Producer app (CLI)
# kafka-console-producer.sh --topic default-topic --bootstrap-server localhost:9092
#
# Start consumer app (CLI)
# kafka-console-consumer.sh --topic default-topic --from-beginning --bootstrap-server localhost:9092
