version: '3.7'

services:
  kafka-producer-service:
    image: kafka-producer-service
    container_name: kafka-producer-service
    hostname: kafka-producer-service
    ports:
      - "8080:8080"
    environment:
      - BROKER=kafka:9092

  kafka-consumer-service:
    image: kafka-consumer-service
    container_name: kafka-consumer-service
    hostname: kafka-consumer-service
    ports:
      - "8081:8081"
    environment:
      - BROKER=kafka:9092
    depends_on:
      - kafka-producer-service

# Create Docker image
# docker build -t <docker_image_id> .
